FROM tensorflow/tensorflow:2.19.0-gpu-jupyter

# 필요한 시스템 패키지 설치
RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    llvm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Sionna 설치
RUN pip install sionna==1.0.1

# Python 의존성 설치
RUN pip install --upgrade ipykernel jupyterlab

EXPOSE 8888

# /app으로 작업 디렉토리 설정 
WORKDIR /app

# JupyterLab 셋업
CMD ["jupyter", "lab", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.allow_origin='*'"]
